*

!Anchor.toml
!Cargo.toml
!Cargo.lock
!README.md
!package.json
!pnpm-lock.yaml
!.npmrc
!.prettierrc
!tsconfig.json

!programs/
!programs/**
!scripts/
!scripts/**

target/
target/**

!Dockerfile.surfpool
!Dockerfile.surfpool.dockerignore
